# Esses dados são de acordo com o desenvolvimento na minha máquina, ajustem as configurações para poder rodar o site na máquina de vocês.
development:
  adapter: postgresql
  encoding: unicode
  database: botquantocusta1bitcoin
  pool: 5
  username: root
  password: root
