development:
  adapter: postgresql
  encoding: unicode
  database: botquantocusta1bitcoin
  pool: 5
  username: root
  password: root

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: [insert your test database name]
#   pool: 5
#   username: [insert your user name]
#   password:

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: 5
